# Configuration

# Site settings
title: Global Network of Domestic Election Monitors
email: gndem@ndi.org
description: >- # this means to ignore newlines until "baseurl:"
  The Global Network of Domestic Election Monitors connects over 245 regional networks and individual nonpartisan citizen observation groups to share best practices and further our common aspirations for representative, responsive, transparent, democratic governance.
baseurl: "/gndem.org" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gndemexchanges

show_excerpts: true
date_format: "%B %-d, %Y"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

languages: ["en", "es", "fr", "ar", "ru"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
