---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
- type: heading
  label: Translations
- type: document
  path: _data/en/strings.yaml
  label: English
- type: document
  path: _data/es/strings.yaml
  label: Spanish
  match: "**/*"
- type: document
  path: _data/fr/strings.yaml
  label: French
  match: "**/*"
- type: document
  path: _data/ar/strings.yaml
  label: Arabic
  match: "**/*"
- type: document
  path: _data/ru/strings.yaml
  label: Russian
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
