---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: heading
  label: Members & Organizations
- type: document
  path: _data/principles_networks.yml
  label: 'DoGP: Networks'
- type: document
  path: _data/principles_organizations.yaml
  label: 'DoGP: Organizations'
- type: document
  path: _data/regional_networks.yml
  label: Regional Networks
- type: document
  path: _data/gndem_members.csv
  label: Members
- type: heading
  label: Translations
- type: document
  path: _data/en/strings.yaml
  label: English
- type: document
  path: _data/es/strings.yaml
  label: Spanish
- type: document
  path: _data/fr/strings.yaml
  label: French
- type: document
  path: _data/ar/strings.yaml
  label: Arabic
- type: document
  path: _data/ru/strings.yaml
  label: Russian
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
